first idea of creating queries for oracle, sadly this doesn't compile since: ``` error[E0210]: type parameter `T` must be used as the type parameter for some local type (e.g. `MyStruct<T>`); only traits defined in the current crate can be implemented for a type parameter   --> src/oracle/query_builder/insert_statement/mod.rs:11:1    | 11 | / impl<T, Tab, DB> QueryFragment<DB> for ValuesClause<T, Tab> 12 | |     where 13 | |         DB: Backend, 14 | |         Tab: Table, ...  | 29 | |     } 30 | | }    | |_^ ```