allowing to run a statement returning a named cursor.
so far the test compiles and runs, but two big points (afar from reordering `use` and some cleanup):
* the output is garbage: somehow we broke the UTF8 stuff, at least while comparing the strings we yiel:
```
thread 'test::use_named_queries' panicked at 'assertion failed: `(left == right)`
  left: `"¿¿¿¿¿¿ ¿¿¿¿¿"`,
 right: `"السلام عليكم"`', src/test/mod.rs:2238:9
```
* in oracle/connection/mod.rs:154 we do
```
        use super::types::OciDataType;
        metadata.push(OciDataType::Text);
```
 this satisfies the test but is not true for all statements